export const DRAGON_SET_VALUE = 'DRAGON/SET_VALUE';
export const DRAGON_ADD = 'DRAGON/ADD';
export const DRAGON_SET_ERROR = 'DRAGON/SET_ERROR';
export const DRAGON_DELETE = 'DRAGON/DELETE';

export const KNIGHT_SET_VALUE = 'KNIGHT/SET_VALUE';
export const KNIGHT_ADD = 'KNIGHT/ADD';
export const KNIGHT_SET_ERROR = 'KNIGHT/SET_ERROR';
export const KNIGHT_DELETE = 'KNIGHT/DELETE';

